### PR TITLE
Full possibilities

### PR DESCRIPTION
**Pull request by psieg**
#21. Ideally @kirstin clones it locally and tells us what she thinks before merging

### CODE REVIEW

**Comment by knub** [comment]
Hi, does this show all possible ways to put the lectures into the specialization groups? If @kirstin has no objections, I would merge this.
I haven't checked the code: are you confident, that it does not offer invalid configurations?

**Comment by psieglerfinn** [comment]
the changes to logic.js do not change offered configurations, I assume the algorithm was already correct. This offers the full table as per @kirstin's request in the frontend, they have been computed all along

**Comment by psieg** [comment]
the changes to logic.js do not change offered configurations, I assume the algorithm was already correct. This offers the full table as per @kirstin's request in the frontend, they have been computed all along

**Comment by kirstin** [comment]
I took a look at it. It does exactly what I was looking for.
I like having this optional long list.
As far as I could tell, the table is coorect. For my Belegung it creates a table of 97 possibilities, because I have many lectures that offer the same Vertiefungsgebiete and can then be either ITSE, VT1 or VT2 and this creates all the different options.

I have no objections to merging this.

**Pull request merged**
